import { useEffect, useState } from 'react'
import packageInfo from '../../package.json'

const APK_URL='https://nexus-tac.netlify.app/downloads/nexus-tac.apk'
const SHARE_TEXT='Download Nexus Tac for Android'

export default function Footer({ onPrivacy,onTerms }) {
  const [popup,setPopup]=useState(null)
  const [copied,setCopied]=useState(false)
  const encodedUrl=encodeURIComponent(APK_URL),encodedText=encodeURIComponent(SHARE_TEXT)
  useEffect(()=>{if(!popup)return;const close=event=>event.key==='Escape'&&setPopup(null);document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[popup])
  const copyLink=async()=>{await navigator.clipboard.writeText(APK_URL);setCopied(true);setTimeout(()=>setCopied(false),1600)}
  const shareNative=async()=>{if(navigator.share){try{await navigator.share({title:'Nexus Tac',text:SHARE_TEXT,url:APK_URL})}catch{}}else window.open('https://www.instagram.com/','_blank','noopener,noreferrer')}

  return <><footer><div className="footer-tech"><span>ADAPTIVE AI ENGINE</span><i/><span>MINIMAX + HUMAN-STYLE HEURISTICS</span></div><nav aria-label="Legal"><button onClick={onPrivacy}>Privacy Policy</button><button onClick={onTerms}>Terms & Conditions</button></nav><div className="footer-share-actions"><button onClick={()=>setPopup('qr')} aria-label="Show APK QR code" title="APK QR code"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM15 14h2v2h-2zM19 14h1v3h-3v3h-3v-2h2v-2h3zM19 19h1v1h-1z"/></svg></button><button onClick={()=>setPopup('share')} aria-label="Share APK" title="Share APK"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.6-4.5M8.2 13.2l7.6 4.5"/></svg></button></div><span className="version-badge" title="Nexus Tac version">v{packageInfo.version}</span><span className="creator-info">Created by Soumya Pal</span></footer>{popup&&<div className="footer-popup-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setPopup(null)}><section className="footer-popup glass" role="dialog" aria-modal="true" aria-label={popup==='qr'?'APK QR code':'Share Nexus Tac'}><button className="footer-popup-close" onClick={()=>setPopup(null)} aria-label="Close">×</button>{popup==='qr'?<><div className="footer-popup-kicker">SCAN TO DOWNLOAD</div><h2>Nexus Tac for Android</h2><div className="apk-qr-wrap"><img src="/qr.jpeg" alt="QR code for the Nexus Tac APK download"/></div><a className="apk-direct-link" href={APK_URL} target="_blank" rel="noreferrer">{APK_URL}</a></>:<><div className="footer-popup-kicker">SHARE THE GAME</div><h2>Send Nexus Tac</h2><div className="social-share-grid"><a className="whatsapp" href={`https://wa.me/?text=${encodedText}%20${encodedUrl}`} target="_blank" rel="noreferrer"><b>W</b><span>WhatsApp</span></a><button className="instagram" onClick={shareNative}><b>◎</b><span>Instagram</span></button><a className="telegram" href={`https://t.me/share/url?url=${encodedUrl}&text=${encodedText}`} target="_blank" rel="noreferrer"><b>➤</b><span>Telegram</span></a><a className="facebook" href={`https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`} target="_blank" rel="noreferrer"><b>f</b><span>Facebook</span></a><a className="twitter" href={`https://twitter.com/intent/tweet?text=${encodedText}&url=${encodedUrl}`} target="_blank" rel="noreferrer"><b>𝕏</b><span>X</span></a><a className="email" href={`mailto:?subject=${encodedText}&body=${encodedText}%0A${encodedUrl}`}><b>✉</b><span>Email</span></a></div><button className="copy-apk-link" onClick={copyLink}>{copied?'✓ LINK COPIED':'⧉ COPY APK LINK'}</button></>}</section></div>}</>
}
