const MEASUREMENT_ID=import.meta.env.VITE_GA_MEASUREMENT_ID
const CONSENT_KEY='nexus-analytics-consent'
export const analyticsConfigured=Boolean(MEASUREMENT_ID&&/^G-[A-Z0-9]+$/i.test(MEASUREMENT_ID))
export const getAnalyticsConsent=()=>localStorage.getItem(CONSENT_KEY)
export function initAnalytics(){if(!analyticsConfigured||getAnalyticsConsent()!=='granted'||window.gtag)return false;window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag('js',new Date());window.gtag('config',MEASUREMENT_ID,{anonymize_ip:true,allow_google_signals:false,allow_ad_personalization_signals:false});const script=document.createElement('script');script.async=true;script.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(MEASUREMENT_ID)}`;document.head.appendChild(script);return true}
export function setAnalyticsConsent(value){localStorage.setItem(CONSENT_KEY,value);if(value==='granted')initAnalytics()}
export function trackEvent(name,parameters={}){if(getAnalyticsConsent()==='granted'&&window.gtag)window.gtag('event',name,parameters)}
export function setAgeGroup(group){if(getAnalyticsConsent()==='granted'&&window.gtag)window.gtag('set','user_properties',{player_age_group:group})}
export function startPlayTimeTracking(getMode){if(!analyticsConfigured||getAnalyticsConsent()!=='granted')return()=>{};let activeAt=Date.now();const flush=()=>{if(document.hidden)return;const seconds=Math.max(0,Math.round((Date.now()-activeAt)/1000));activeAt=Date.now();if(!seconds)return;const day=new Date().toISOString().slice(0,10),key=`nexus-play-time-${day}`,total=Number(localStorage.getItem(key)||0)+seconds;localStorage.setItem(key,String(total));trackEvent('play_time_daily',{engagement_seconds:seconds,daily_play_seconds:total,game_mode:getMode()})};const timer=setInterval(flush,60000);const visibility=()=>{if(document.hidden)flush();else activeAt=Date.now()};document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',flush);return()=>{flush();clearInterval(timer);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pagehide',flush)}}
export function installErrorTracking(){const error=event=>trackEvent('game_error',{error_type:'runtime',error_message:String(event.message||'Unknown error').slice(0,100)}),rejection=event=>trackEvent('game_error',{error_type:'promise',error_message:String(event.reason?.message||event.reason||'Unknown rejection').slice(0,100)});window.addEventListener('error',error);window.addEventListener('unhandledrejection',rejection);return()=>{window.removeEventListener('error',error);window.removeEventListener('unhandledrejection',rejection)}}
